package carlosrmendoza.com.amusingfacts;

/**
 * Created by Carlos on 11/4/14.
 */
public class FactBook {
    private RandomNoRepeat randomNoRepeat = new RandomNoRepeat(); //creates instance of RandomNoRepeat.java object

    public String[] snappleFacts = { //array containing snappleFacts
            "Animals that lay eggs don't have belly buttons.",
            "Beavers can hold their breath for 45 minutes under water.",
            "Slugs have four noses.",
            "Camels have three eyelids.",
            "A honey bee can fly at 15mph.",
            "A queen bee can lay 800-1,500 eggs per day.",
            "A bee has five eyelids.",
            "The average speed of a housefly is 4.5 mph.",
            "Mosquitoes are attracted to people who just ate bananas.",
            "Flamingos turn pink from eating shrimp.",
            "Emus and kangaroos cannot walk backward.",
            "Cats have over 100 vocal chords.",
            "Camel's milk does not curdle.",
            "All porcupines float in water.",
            "The world's termites outweigh the world's humans about 10 to 1.",
            "A hummingbird weighs less than a penny.",
            "A jellyfish is approximately 95% water.",
            "Children tend to grow faster in the spring.",
            "Broccoli is the only vegetable that is also a flower.",
            "Almonds are part of the peach family.",
            "Alaska has the highest percentage of people who walk to work.",
            "The San Francisco cable cars are the only mobile national monument.",
            "The state of Maine has 62 lighthouses.",
            "The only food that does not spoil is honey.",
            "The Hawaiian alphabet only has 12 letters.",
            "A ball of glass will bounce higher than a ball of rubber.",
            "Chewing gum while peeling onions will prevent you from crying.",
            "On average a human will spend up to 2 weeks kissing in his/her lifetime.",
            "Fish have eyelids.",
            "There are about 1 million ants for every person in the world.",
            "Termites eat through wood two times faster when listening to rock music!",
            "If you keep a goldfish in a dark room it will eventually turn white.",
            "A snail breathes through its foot.",
            "Fish cough.",
            "An ant's sense of smell is stronger than a dog's.",
            "It is possible to lead a cow up stairs but not down.",
            "Shrimp can only swim backward.",
            "Frogs cannot swallow with their eyes open.",
            "A cat's lower jaw cannot move sideways.",
            "The bullfrog is the only animal that never sleeps.",
            "Elephants are capable of swimming 20 miles per day.",
            "Elephants are the only mammals that can't jump.",
            "Giraffes have no vocal chords.",
            "Cats can hear ultrasound.",
            "Despite its hump, a camel has a straight spine.",
            "Mosquitoes have 47 teeth.",
            "There are 63,360 inches in a mile.",
            "About 11% of the people in the world are left-handed.",
            "The average women consumes six pounds of lipstick in her lifetime.",
            "The average smell weighs 760 nanograms.",
            "A human brain weighs about three pounds.",
            "1/4 of the bones in your body are in your feet.",
            "You blink over 10,000,000 times a year.",
            "A sneeze travels out of your mouth at over 100 miles an hour.",
            "Brain waves can be used to power an electric train.",
            "The tongue is the fastest healing part of the body.",
            "Pigs can get sunburn.",
            "The lifespan of a taste bud is about ten days.",
            "The average human produces 10,000 gallons of saliva in a lifetime.",
            "Strawberries contain more vitamin C than oranges.",
            "A one-day weather forecast requires about 10 billion math calculations.",
            "Americans, on average, eat 18 acres of pizza a day.",
            "There are 18 different animal shapes in the animal cracker zoo.",
            "The longest one syllable word is \"screeched.\"",
            "No word in the English language rhymes with month.",
            "There is a town called \"Big Ugly\" in West Virginia.",
            "The average person uses 150 gallons of water per day for personal use.",
            "The average person spends 2 weeks over his/her lifetime waiting for a traffic light to change.",
            "You share your birthday with at least 9 million other people in the world.",
            "The average person makes 1,140 phone calls per year.",
            "The average person spends about 2 years on the phone in a lifetime.",
            "No piece of paper can be folded more than seven times.",
            "Alaska is the most eastern and western state in the U.S.",
            "There are 119 grooves on the edge of a quarter.",
            "About 18 percent of animal owners share their bed with their pet.",
            "Alaska has more caribou than people.",
            "August has the highest percentage of births.",
            "Googol is a number (1 followed by 100 zeros).",
            "Oysters can change from one gender to another and back again.",
            "The Mona Lisa has no eyebrows.",
            "Until the 19th century, solid blocks of tea were used as money in Siberia.",
            "A mile on the ocean and a mile on land are not the same distance.",
            "A ten gallon hat holds less than one gallon of liquid.",
            "The average raindrop falls at seven mph.",
            "There are more telephones than people in Washington, D.C.",
            "Fish can drown.",
            "A kangaroo can jump 30 feet.",
            "Lizards communicate by doing push-ups.",
            "Squids can have eyes the size of a volleyball.",
            "The average American will eat 35,000 cookies in his/her lifetime.",
            "A turkey can run at 20 mph.",
            "When the moon is directly overhead, you weigh slightly less.",
            "You burn about 20 calories per hour chewing gum.",
            "In a year, the average person walks four miles making his or her bed.",
            "About half of all Americans are on a diet on any given day.",
            "A one-minute kiss burns about 26 calories.",
            "Frowning burns more calories than smiling.",
            "There are more than 30,000 diets on public record.",
            "You will burn about 7% more calories walking on hard dirt than on pavement.",
            "You would weigh less on the top of a mountain than at sea level.",
            "You burn more calories sleeping than watching TV.",
            "Licking a stamp burns 10 calories.",
            "Smelling apples and/or bananas can help you lose weight.",
            "Frogs never drink.",
            "Only male turkeys gobble.",
            "At birth, a Dalmation is always pure white.",
            "The oldest known animal was a tortoise, which lived to be 152 years old.",
            "Bamboo makes up 99 percent of a panda's diet.",
            "The largest fish is the whale shark - it can be over 50 feet long and weigh two tons.",
            "The starfish is the only animal that can turn its stomach inside out.",
            "Honeybees are the only insects that create a form of food for humans.",
            "The hummingbird is the only bird that can fly backwards.",
            "The only continent without reptiles or snakes is Antarctica.",
            "The only bird that can swim and not fly is a penguin.",
            "A duck can't walk without bobbing its head.",
            "Beavers were once the size of bears.",
            "Seals sleep only one and a half minutes at a time.",
            "Pigeons have been trained by the U.S. Coast Guard to spot people lost at sea.",
            "A pigeon's feathers are heavier than its bones.",
            "A hummingbird's heart beats 1,400 times a minute.",
            "Dragonflies have six legs but can't walk.",
            "Dolphins can jump up to 20 feet in the air.",
            "Koala and humans are the only animals with unique fingerprints.",
            "Penguins have an organ above their eyes that converts seawater to fresh water.",
            "A crocodile cannot move its tongue.",
            "Honeybees navigate by using the sun as a compass.",
            "An ant can lift 50 times its own weight.",
            "A single coffee tree produces only about a pound of coffee beans per year.",
            "Strawberries are the only fruits whose seeds grow on the outside.",
            "The city of Los Angeles has about 3x more automobiles than people.",
            "Hawaii is the only U.S. state that grows coffee commercially.",
            "Hawaii is the only state with one school district.",
            "Holland is the only country with a national dog.",
            "The square dance is the official dance of the state of Washington.",
            "Hawaii is the only U.S. state never to report a temperature of zero degrees F or below.",
            "\"Q\" is the only letter in the alphabet not appearing in the name of any U.S. state.",
            "Texas is the only state that permits residents to cast absentee ballots from space.",
            "Lake Superior is the world's largest lake.",
            "The smallest county in America is New York County, better known as Manhattan.",
            "Panama is the only place in the world where you can see the sun rise on the Pacific and set on the Atlantic.",
            "The tallest man was 8 ft. 11 in.",
            "Theodore Roosevelt was the only president who was blind in one eye.",
            "The first sport to be filmed was boxing in 1894.",
            "The fastest served ball in tennis was clocked at 154 mph in 1963.",
            "In 1985, the fastest bicyclist was clocked at 154 mph.",
            "The speed limit in NYC was eight mph in 1895.",
            "Americans spend more than $630 million a year on golf balls.",
            "In 1926, the first outdoor mini-golf courses were built on rooftops in NYC.",
            "Swimming pools in the U.S. contain enough water to cover San Francisco.",
            "The first TV soap opera debuted in 1946.",
            "The first MTV video was \"Video Killed the Radio Star\" by the Buggles.",
            "The first TV show ever to be put into reruns was \"The Lone Ranger.\"",
            "One alternative title that had been considered for NBC's hit \"Friends\" was \"Insomnia CafÃ©.\"",
            "The first TV network kids show in the U.S. was \"Captain Kangaroo.\"",
            "The temperature of the sun can reach up to 15 million degrees Fahrenheit.",
            "The first penny had the motto \"Mind your own business.\"",
            "The first vacuum was so large, it was brought to a house by horses.",
            "Your eye expands up to 45% when looking at something pleasing.",
            "Before mercury, brandy was used to fill thermometers.",
            "You'd have to play ping-pong for about 12 hours to lose one pound.",
            "One brow wrinkle is the result of 200,000 frowns.",
            "The first human-made object to break the sound barrier was a whip.",
            "The most sensitive parts of the body are the mouth and the fingertips.",
            "The eye makes movements 50 times every second.",
            "Chinese is the most spoken language in the world.",
            "The world's biggest pyramid is not in Egypt, but in Mexico.",
            "In 1634, tulip bulbs were a form of currency in Holland.",
            "The first bike was called a hobbyhorse.",
            "The first sailing boats were built in Egypt.",
            "The first ballpoint pens were sold in 1945 for $12.00.",
            "The first VCR was made in 1956 and was the size of a piano.",
            "The first jukebox was located in San Francisco in 1899.",
            "A rainbow can only be seen in the morning or late afternoon.",
            "The Capitol building in Washington, D.C. has 365 steps to represent every day of the year.",
            "The most used letters in the English language are E, T, A, O, I and N.",
            "A male kangaroo is called a boomer.",
            "A female kangaroo is called a flyer.",
            "There are over 61,000 pizzerias in the U.S.",
            "Antarctica is the driest, coldest, windiest, and highest continent on earth.",
            "The Sahara Desert stretches farther than the distance from California to New York.",
            "Thailand means \"Land of the Free.\"",
            "Popcorn was invented by the American Indians.",
            "Jupiter spins so fast that there is a new sunrise nearly every 10 hours.",
            "The year that read the same upside down was 1961. That won't happen again until 6009.",
            "You don't have to be a lawyer to be a Supreme Court Justice.",
            "Eleven of the 50 U.S. states are named after an actual person.",
            "If you doubled one penny every day for 30 days, you would have $5,368,709.",
            "The first person crossed Niagara Falls by tightrope in 1859.",
            "The U.S. is the largest country named after a real person (Amerigo Vespucci).",
            "The largest cheesecake ever made weighed 57,508 lbs.",
            "The first country to use postcards was Austria.",
            "The only one-syllabled U.S. state is Maine.",
            "The mouth of the Statue of Liberty is 3 feet wide.",
            "Atlantic salmon are capable of leaping 15 feet high.",
            "A stamp shaped like a banana was once issued in the country of Tonga.",
            "For every human being in the world there is approximately one chicken.",
            "Over 1 million Earths would fit inside the Sun.",
            "Before 1687 clocks were made with only an hour hand.",
            "Add up opposing sides of a dice cue and you'll always get seven.",
            "About 1.3 billion pounds of peanuts are produced in Georgia each year.",
            "The average koala sleeps 22 hours each day.",
            "Galapagos turtles can take up to three weeks to digest a meal.",
            "The largest ball of twine in the US weighs over 17,000.",
            "Giraffes can lick their own eyes.",
            "Tennessee banned the use of a lasso to catch fish.",
            "TV dinners originated in the Artic.",
            "Blackboard chalk contains no chalk.",
            "A jackrabbit can travel more than 12 feet in one hop.",
            "An electric eel can release a charge powerful enough to start 50 cars.",
            "Porcupines each have 30,000 quills.",
            "The game of basketball was first played using a soccer ball and two peach baskets.",
            "Twinkle Twinkle Little Star was composed by Mozart when he was five years old.",
            "The Basenji is the only type of dog that does not bark.",
            "America's 1st roller coaster was built in 1827 to carry coal from a mine to boats below.",
            "There are towns named Sandwich in Illinois and Massachusetts.",
            "13 percent of the world's tea comes from Kenya.",
            "Tsiology is anything written about tea.",
            "The Caspian Sea is actually a lake.",
            "Caterpillars have over 2,000 muscles.",
            "Detroit has the greatest number of registered bowlers in the U.S.",
            "The blue whale's heart is the size of a small car.",
            "There are seven letters that look the same upside down as right side up.",
            "Great Falls, Montana, is the windiest city in the U.S.",
            "The biggest pig in recorded history weighed almost one ton.",
            "Cows give more milk when they listen to music.",
            "The number of times a cricket chirps in 15 seconds, plus 37, will give you the current air temperature.",
            "An ostrich's brain is smaller than its eye.",
            "Besides humans, elephants are the only animals that can be taught to stand on their head.",
            "\"Challenger Deep\" is the deepest point on Earth and can hold 25 Empire State Buildings end to end.",
            "The only cactus plantation in the world is in Mississippi.",
            "The Nickname of President Hayes's wife was \"Lemonade Lucy.\"",
            "If you put all the streets in New York City in a straight line, they would stretch to Japan.",
            "The watermelon seed-spitting world record is about 70 feet.",
            "The first typewriter was called the \"literary piano.\"",
            "The \"silk\" of a spider is stronger than steel threads of the same diameter.",
            "Britain was the first country to register a patent on polyester.",
            "Snoopy is the most common dog name beginning with the letter S.",
            "The 1st public message to be transmitted via Morse code was \"A patient waiter is no loser.\"",
            "Mongolians invented lemonade around 1299 A.D.",
            "There are more French restaurants in New York City than in Paris.",
            "There is a town in Alaska called Chicken.",
            "The first TV remote control, introduced in 1950, was called Lazy Bones.",
            "The only bird who can see the color blue is the owl.",
            "Among North Atlantic lobsters, about 1 in 5,000 is born bright blue.",
            "There are more saunas than cars in Finland.",
            "The first food eaten in space by a U.S. astronaut was applesauce.",
            "Lemon wood is carved into chess pieces.",
            "The original recipe for chocolate contained chili powder instead of sugar.",
            "Underwater hockey is played with a 3-pound puck.",
            "Playing in a marching band is considered moderate exercise.",
            "The act of chewing an apple is a more efficient way to stay awake than caffeine.",
            "Bowling pins need to tip over a mere 7 1/2 degrees to fall down.",
            "Your breathing rate increases when you start to type.",
            "About 90% of all garlic consumed in the U.S. comes from Gilroy, CA.",
            "Manhattan is the only borough in New York City that doesn't have a Main Street.",
            "Double Dutch jump rope is considered a cross-training sport.",
            "One lemon tree will produce about 1,500 lemons a year.",
            "Horseback riding can improve your posture.",
            "Colors like red, yellow and orange make you hungry.",
            "Dim lights reduce your appetite.",
            "At birth a human has 350 bones, but only 206 bones when full grown.",
            "Each year, the average American eats about 15 pounds of apples.",
            "All lemons are harvested by hand.",
            "It took the first man to walk around the world four years, three months and 16 days to complete his journey.",
            "Grizzly bears run as fast as the average horse.",
            "Today's \"modern\" wrestling moves have been seen in tomb drawings from ancient Egypt.",
            "China only has one time zone.",
            "Canada has the longest coastline of any country in the world.",
            "The amount of concrete used in the Hoover Dam could build a highway from New York to California.",
            "The original name of Nashville, Tennessee was Big Salt Lick.",
            "If you drive from Los Angeles to Reno, NV, you will be heading west.",
            "A compass needle does not point directly north.",
            "Mt. Everest has grown one foot over the last 100 years.",
            "In ancient Rome, lemons were used as an antidote to all poisons.",
            "The height of the Eiffel Tower varies by as much as 6 inches depending on the temperature.",
            "Wisconsin has points located farther east than parts of Florida.",
            "Four Corners, AZ, is the only place where a person can stand in 4 states at the same time.",
            "In 1908, the first lollipop-making machine started in New Haven, CT.",
            "One out of every eight residents in the U.S. lives in California.",
            "Africa is divided into more countries than any other continent.",
            "Heavier, not bigger lemons, produce more juice.",
            "Vermont is the only New England state without a seacoast.",
            "No only child has been a U.S. President.",
            "Leonardo da Vinci could draw with one hand while writing with the other.",
            "In 1860, Abraham Lincoln grew a beard at the suggestion of an 11-year-old girl.",
            "David Rice Atchison was President of the United States for only one day.",
            "The sail fish has been clocked at speeds of over 60 miles per hour.",
            "The Library of Congress has 600 miles of shelves.",
            "Pennsylvania is misspelled on the Liberty Bell, because that is how they spelled it in the 18th century.",
            "William Shakespeare was born and died on the same day: April 23.",
            "Ketchup was once sold as a medicine.",
            "Napoleon suffered from a fear of cats.",
            "In 1900, 1/3 of all automobiles in New York City were powered by electricity.",
            "The 4th Earl of Sandwich invented the sandwich so he could eat and gamble at the same time.",
            "In the Middle Ages, chicken soup was considered an aphrodisiac.",
            "All dog breeds except chow-chows have black lips to prevent them from getting sunburned.",
            "Connecticut was the first state to pass a Lemon Law in 1982.",
            "Ancient Egyptians believed the \"vein of love\" ran from the third finger on the left hand to the heart.",
            "The word \"facetious\" features all the vowels in alphabetical order.",
            "The standard Chinese typewriter has 1,500 characters.",
            "A flea can jump 30,000 times without stopping.",
            "\"O\" is the oldest letter of the alphabet, dating back to 3000 B.C.",
            "The Japanese word \"judo\" means \"the gentle way.\"",
            "No two lip impressions are the same.",
            "It took Leonardo da Vinci 12 years to paint the lips of Mona Lisa.",
            "Lemon sharks can give birth to about 36 babies at one time.",
            "Top-performing companies are called \"blue chips\" after the costliest chips in casinos.",
            "The name for the space between your eyebrows is \"nasion.\"",
            "There is a town called Jackpot in Nevada.",
            "The word \"purple\" does not rhyme with any other word in the English language.",
            "In the U.S., there are about 15,000 vacuum cleaner-related accidents each year.",
            "The Lemon-Yellow Tree Frog is only active in the darkness of night.",
            "The legs of bats are too weak to support their weight, so they hang upside down.",
            "75% of people wash from top to bottom in the shower.",
            "On average, you'll spend a year of your life looking for misplaced objects.",
            "Chewing gum was invented in New York City in 1870 by Thomas Adams.",
            "The Statue of Liberty features 7 points in her crown- one for each of the continents.",
            "The world's first escalator was built in Coney Island, NY, in 1896.",
            "The top of the Empire State Building was originally built as a place to anchor blimps.",
            "The area code in Cape Canaveral, Fl, is 321.",
            "Ohio is the only U.S. state that does not have a rectangular flag.",
            "Long Island is the largest island in the Continental U.S.",
            "The beaver is the official animal of Canada.",
            "Maine produces more toothpicks than any other state in the U.S.",
            "The last letter to be added to our alphabet was J.",
            "Farmington, Maine celebrates Chester Greenwood Day to honor the inventor of earmuffs.",
            "Of all the trees in Australia, 75% are eucalyptus.",
            "There are more doughnut shops per capita in Canada than in any other country.",
            "There is an underground mushroom in Oregon that measures 3.5 miles across.",
            "Of the 92 counties in Indiana, only 5 observe daylight savings time.",
            "California and Arizona grow approximately 95% of the fresh lemons in the U.S.",
            "The term 007 was derived from 20007, the home zip code of many Washington, D.C. agents.",
            "Leonardo da Vinci discovered that a tree's rings reveal its age.",
            "The popsicle was invented in 1905 by an 11-year-old boy.",
            "The medical term for writer's cramp is graphospasm.",
            "A male firefly's light is twice as bright as a female's.",
            "It is estimated that the world's oceans contain 10 billion tons of gold.",
            "Most cats don't like lemonade.",
            "The watersheds that supply water to New York City are roughly the size of Delaware.",
            "Cold water weighs less than hot water.",
            "Storm clouds hold about 6 trillion raindrops.",
            "The weight of the moon is 81 billion tons.",
            "Bamboo can grow three feet in one day.",
            "A tune that gets stuck in your head is called an earworm.",
            "You exhale air at 15 m.p.h.",
            "A baboon is a variety of lemon.",
            "Butterflies were formerly known by the name Flutterby.",
            "A teaspoon contains 120 drops of water.",
            "Mexican jumping beans jump to get out of sunlight.",
            "The pineapple is a very big berry.",
            "\"Arachibutlphobia\" is the fear of peanut butter sticking to the roof of your mouth.",
            "Pearls dissolve in vinegar.",
            "Borborygmi is the noise that your stomach makes when you are hungry.",
            "The oil in cashews helps prevent tooth decay.",
            "The center of some golf balls contain honey.",
            "International tug of war rules state that the rope must be over 100-feet long.",
            "In 2003, a 6-year-old from Naples, FL was ticketed for not having a permit for her lemonade stand.",
            "On Valentine's Day, there is no charge to get married in the Empire State Building's chapel.",
            "Heat, not sunlight, ripens tomatoes.",
            "Grapes are the most popular fruit in the world.",
            "A housefly hums in the key of F.",
            "Endocarp is the edible pulp inside a lemon.",
            "Thomas Edison coined the word \"hello\" and introduced it as a way to answer the phone.",
            "\"Way\" is the most frequently used noun in the English language.",
            "The \"high five\" was introduced by a professional baseball player in 1977.",
            "\"Disco\" means \"I learn\" in Latin.",
            "It costs the U.S. government 2.5 cents to produce a quarter.",
            "The \"lemon yellow\" crayon was introduced in 1949 and retired in 1990.",
            "It is illegal for a portrait of a living person to appear on U.S. postage stamps.",
            "Baboons were once trained by Egyptians to wait on tables.",
            "The official state gem of Washington is petrified wood.",
            "Mount Katahdin in Maine is the first place in the U.S. to get sunlight each morning.",
            "Each year, the average person walks the distance from NY to Miami.",
            "Lemons are more acidic than vinegar.",
            "New York City's public school students represent about 188 different countries.",
            "The first person in the U.S. arrested for speeding was a NYC cab driver.",
            "In the U.S., all interstate highways that run east to west are even-numbered.",
            "Jack is the most common name in nursery rhymes.",
            "A sea lemon is a mollusk that feeds on sponges.",
            "Three out of every six Americans live within fifty miles of where they were born.",
            "The raised bump reflectors on U.S. roads are named \"Botts dots.\"",
            "Nearly 9,000 people injure themselves with a toothpick each year.",
            "It is impossible to sneeze with your eyes open.",
            "The dragonfly can reach speeds of up to 36 mph.",
            "Hippos can open their mouths 180 degrees.",
            "About 80 women go into labor on NYC subways every year.",
            };

    public String[] historyFacts = { //array containing historyFacts

            "The 16th century Escorial palace of King Phillip II of Spain had 1,200 doors.",
            "The world’s first travel agencies were Cox & Kings, founded in 1758, and Thomas Cook, founded in 1850.",
            "A dog was the first in space and a sheep, a duck and a rooster the first to fly in a hot air balloon.",
            "Music was sent down a telephone line for the first time in 1876, the year the phone was invented.",
            "Beer was the first trademarked product – British beer Bass Pale Ale received its trademark in 1876.",
            "Playing-cards were known in Persia and India as far back as the 12th century. A pack then consisted of 48 instead of 52 cards.",
            "Excavations from Egyptian tombs dating to 5,000 BC show that the ancient Egyptian kids played with toy hedgehogs.",
            "Accounts from Holland and Spain suggest that during the 1500s and 1600s urine was commonly used as a tooth-cleaning agent.",
            "Julius Caesar was the first to encode communications, using what has become known as the Caesar Cipher.",
            "The first mention of soap was on Sumerian clay tablets dating about 2,500 BC. The soap was made of water, alkali and cassia oil.",
            "The first animal in space was the female Samoyed husky named Laika, launched by the Soviets in 1957.",
            "In 1958, the US sent two mice called Laska and Benjy into space.",
            "In 1961, the US launched a male chimpanzee called Ham into space.",
            "In 1963, the French launched a cat called Feliette into space.",
            "Great Britain was the first county to issue postage stamps, on 1 May 1840. Hence, UK stamps are the only stamps in the world not to bear the name of the country of origin.",
            "Only one of the Seven Wonders of the World still survives: the Great Pyramid of Giza.",
            "The first parachute jump from an airplane was made by Captain Berry in St. Louis, Missouri, in 1912.",
            "On June 21, 1913, over Los Angeles, Georgia Broadwick became the first women to parachute from an airplane.",
            "The first written account of the Loch Ness Monster, or Nessie, was made in 565AD.",
            "The world’s first skyscraper was the 10-storey Home Insurance office, built in Chicago in 1885. (During Roman times buildings were up to 8 stories high.)",
            "Neil Armstrong was the first person to set foot on the moon.",
            "1 BC - The revised Julian calendar introduced (on March 1).",
            "44 BC - Julius Caesar assassinated.",
            "776 BC - First Olympiad in Greece.",
            "753 BC - Rome founded by Romulus.",
            "563 BC - Buddha (Siddhārtha Gautama) born in India.",
            "551 BC - Confucius born in China.",
            "535 BC - The first Roman calendar introduced: it had 10 months, with 304 days in a year that began in March.",
            "532 BC - Pythagoras of Crotona describes the relations between sides of right-angled triangle, and tone vibrations.",
            "525 BC - Tragedy and comedy theater performed. Celebratory songs and dances held in honor of Dionysus, the Greek god of wine and merrymaking, evolved into the earliest plays.",
            "483 - BC Buddha dies.",
            "470 - BC Socrates born near Athens. (He introduced the great tradition of Western philosophy. He was executed in 399 BC)",
            "440 BC - Greek philosopher Leucippus and his student Democritus puts forward the notion that all matter consists of fundamental particles called atoms. (The word atom comes from the Greek word meaning /”indivisible./”).",
            "399 BC – Socrates is required to drink hemlock to end his life after being found guilty of corrupting the youth of Athens.",
            "350 BC - Aristotle writes Meteorologica, the first book on weather.",
            "347 BC – 322 BC Aristotle identifies and classifies living forms. Plato establishes a philosophy academy.",
            "330 BC - Darius II dies – end of Persian empire.",
            "300 BC - Great Wall of China constructed in parts.",
            "300 BC - Euclid, a Greek from Alexandria, writes Elements, introducing geometry (which means “land measurement”).",
            "264 BC - First Roman gladiatorial games.",
            "240 BC - Livius Andronicus is the first Roman poet.",
            "221 BC - China unites when the king of Ch’in, Ying Zheng, defeat the kings of other 6 kingdoms – Zheng becomes Qin Shi Huang, first emperor of a unified China.",
            "212 BC - Archimedes explains the area of circle, principles of lever, the screw, and buoyancy.",
            "194 BC - Eratosthenes determines the size of Earth and put forward theories of the climate.",
            "150 BC - Chinese make paper from macerated hemp fibers, plant bark, molded over old fishnets.",
            "120 BC - Hipparchus of Rhodes explains the pattern of the cosmos in latitude and longitude; and makes triangular measurement of celestial navigation",
            "100 BC - The trip hammer and the use of paper developed in China.",
            "Most scholars believe Jesus Christ was born between 6 and 4 BC.",
            "1900 - Escalator invented by Charles Seeberger.",
            "1900 - Paperclip patented by Norwegian Johann Vaaler.",
            "1900 - Charlotte Cooper becomes the first woman to win an Olympic gold (tennis)",
            "1901 - Edison General Electric Co introduces its Christmas tree lights.",
            "1901 - The first facelift is performed by Eugene Hollander in Berlin on a Polish aristocrat.",
            "1901 - First time getaway car is used by 3 bank robbers in Paris.",
            "1902 - The teddy bear is created by a Russian immigrant to the USA, after seeing a newspaper cartoon depicting President Theodore “Teddy” Roosevelt.",
            "1902 - Automatic vending machine invented.",
            "1902 - Willis Carrier invents the air conditioner.",
            "1903 - First Tour de France.",
            "1903 - William Harley and Arthur Davidson launch the Harley-Davidson motorcycle company.",
            "1903 - First Crayola crayons go on sale.",
            "1904 - Teabags invented by Thomas Suillivan.",
            "1904 - The first underwater journey by submarine – from Portsmouth to the Isle of Wight.",
            "1904 - Henry Royce and Charles Rolls start Rolls-Royce.",
            "1905 - Norwegian explorer Roald Amundsen discovers the magnetic north pole.",
            "1905 - Albert Einstein publishes “theory of relativity.”",
            "1906 - William Kellogg invents cornflakes.",
            "1906 - Instant coffee invented by Mr G Washington, an Englishman living in Guatemala.",
            "1906 - The first Grand Prix is held at Le Mans, France – won by Romanian driver Ferenc Szisz in a Renault.",
            "1906 - Picasso invents cubism.",
            "1906 - Lewis Nixon invents sonar",
            "1907 - Color photography invented by Auguste and Louis Lumiere.",
            "1907 - Leo Baekeland discovers plastic.",
            "1907 - First blood transfusion.",
            "1908 - Ford Model T rolls out.",
            "1908 - Aisin-Gioro Puyi becomes the last emperor of China – he ruled until 1912 and for 12 days in 1917.",
            "1908 - Einstein proposes quantum theory.",
            "1910 - Mrs John B Dodd starts Father’s Day.",
            "1911 - Republic of China founded.",
            "1911 - First Hollywood studios built.",
            "1911 - Word “Vitamin” used to describe chemicals necessary to diets.",
            "1912 - First crossword puzzle published in New York Journal.",
            "1912 - Dr Gaston Odin discovers the cancer microbe.",
            "1912 - Albert Berry makes the first parachute jump from an airplane.",
            "1912 - First neon advertising sign is displayed in Paris, for Cinzano.",
            "1912 - The Titanic sinks on April, 15.",
            "1912 - Turkey surrenders to Serbia and Bulgaria, ending the Ottoman period.",
            "1912 - First self-service food store opens in California.",
            "1913 - Briton Henry Brearly invents stainless steel.",
            "1913 - Georgia “Tiny” Broadwick becomes the first woman to make a parachute jump.",
            "1913 - Thomas Edison invents the telephone recorder.",
            "1914 - World War I breaks out on 4 August.",
            "1914 - Color photographic process invented by Eastman Kodak.",
            "1914 - First commercial airline flies from Tampa to St Petersburg, Florida.",
            "1914 - US President Woodrow Wilson proclaims Mother’s Day, a revival of a practice that dates back to the Greek empire.",
            "1915 - James Lewis Kraft launches process cheese in Canada.",
            "1916 - George Jung produces the first fortune cookies, in Los Angeles.",
            "1916 - Coca-Cola launches its curvaceous bottle, modeled on the cola nut.",
            "1916 - John D Rockefeller becomes the first billionaire.",
            "1916 - William Boeing found his aircraft construction company.",
            "1917 - Lenin leads the Russian revolution.",
            "1918 - Germany surrenders to the Allies on 11 November at Compiegne, France.",
            "1919 - The Treaty of Versailles signed 28 June, concluding WWI.",
            "1920 - First ice cream on a stick is sold by Harry Burt at his Good Humor Bar.",
            "1921 - Johnson & Johnson launches the band-aid bandage.",
            "1924 - First around-the-world flight.",
            "1924 - First Winter Olympics at Chamonix, France.",
            "1924 - Columbia Pictures and MGM founded.",
            "1924 - Caesar salad invented in Tijuana, Mexico by Caesar Gardini.",
            "1800 - The population of the world is about one billion.",
            "1928 - Scottish biologist Alexander Fleming discovers penicillin.",
            "1929 - New York Stock Exchange crash on “Black Thursday” 24 October.",
            "1937 - An emergency number to the police – 999 – is launched in London.",
            "1939 - Outbreak of World War II.",
            "1942 - Tony the Tiger debuts as mascot for Kellogg’s Frosted Flakes.",
            "1944 - Allied D-Day landings at Normandy, France break German defenses.",
            "35 million people were killed in WWII, 18 million were from Russia.",
            "1945 - German forces finally surrender in May (WWII).",
            "1948 - Israel established.",
            "1963 - President John F Kennedy assassinated.",
            "1967 - Che Guevara is shot dead by Bolivian troops.",
            "1968 - Dr Martin Luther King assassinated.",
            "1973 - Watergate scandal breaks.",
            "1975 - Junko Tabei of Japan becomes first woman to reach Everest summit.",
            "1977 - Apple II becomes the first mass-produced home computer.",
            "1977 - Star Wars debuts.",
            "1980 - Philips invents the CD.",
            "1983 - HIV virus identified.",
            "1987 - World population reaches 5 billion.",
            };

    public String[] sportsFacts = { //array containing sportsFacts
            "Fishing is the biggest participant sports in the world.",
            "Football (soccer) is the most attended and watched (on TV) sport in the world.",
            "The first AFL/NFL championship to be called a “Super Bowl” was Superbowl III; on January 12, 1969 the New York Jets beat the Baltimore Colts 16 – 7 at the Orange Bowl.",
            "Super Bowl I was held on January 15, 1967 in Los Angeles where the Green Bay Packers beat Kansas City Chiefs by 35 to 10.",
            "The Dalas Cowboys and the Pittsburgh Steelers have the most Super Bowl appearances – 8 each.",
            "The Pittsburgh Stellers have won the most Super Bowl titles – 6 championships. The Dallas Cowboys and San Francisco 49ers each won 5 times.",
            "Boxing became a legal sport in 1901.",
            "More than 100 million people hold hunting licenses.",
            "Jean Genevieve Garnerin was the first female parachutists, jumping from a hot air balloon in 1799.",
            "The record for the most major league baseball career innings is held by Cy Young, with 7,356 innings.",
            "The Major League Baseball teams use about 850,000 balls per season.",
            "The first instance of global electronic communications took place in 1871 when news of the Derby winner was telegraphed from London to Calcutta in under 5 minutes.",
            "In 1898, one of the first programs to be broadcasted on radio was a yacht race that took place in British waters.",
            "Sports command the biggest television audiences, led by the summer Olympics, World Cup Football and Formula One racing.",
            "Gymnasiums were introduced in 900BC and Greek athletes practiced in the nude to the accompaniment of music. They also performed naked at the Olympic Games.",
            "The very first Olympic race, held in 776 BC, was won by Corubus, a chef.",
            "The first modern Olympic Games were held in Athens, Greece in 1896. There were 311 male but no female competitors.",
            "The high jump method of jumping head first and landing on the back is called the Fosbury Flop.",
            "About 42,000 tennis balls are used in the plus-minus 650 matches in the Wimbledon Championship.",
            "A baseball ball has exactly 108 stitches, a cricket ball has between 65 and 70 stitches.",
            "Basketball and rugby balls are made from synthetic material. Earlier, pigs’ bladders were used as rugby balls.",
            "The baseball home plate is 17 inches wide.",
            "The very first motor car land speed record was set by Ferdinand Verbiest.",
            "The record for the most NASCAR wins is held by Richard Petty: 200 wins (and 7 championships).",
            "Sébastien Loeb won the World Rally Championship a record 9 times, taking the title every year between 2004 and 2012.",
            "The Romans played a game resembling golf, using a stick to hit a feather-stuffed ball.",
            "The word GOLF derives from an old German word “kolb,” meaning club.",
            "Bill Klem served the most seasons as major league umpire – 37 years, starting in 1905. He also officiated 18 World Series.",
            "The oldest continuous trophy in sports is the America’s Cup. It started in 1851, with Americans winning for a straight 132 years until Australia took the Cup in 1983.",
            "Volleyball was invented by William George Morgan of Holyoke, Massachusetts in 1895.",
            "A badminton shuttle easily travels 180 km/h (112 mph).",
            "Ferenc Szisz from Romania, driving a Renault, won the first Formula One Grand Prix held at Le Mans, France in 1906.",
            "Stéphane Peterhansel holds the record for most Dakar Rally wins; he won the motorcycle category (on a Yamaha) 6 times and has won the car category 5 times",
            "Competing in three Olympics, between 1956 and 1964, Soviet gymnast Larissa Latynina won 18 medals (9 gold, 5 silver and 4 bronze).",
            "Michael Phelps holds the record for most Olympic medals, 22 medals (18 gold, 2 silver and 2 bronze).",
            "The original World Series was a contest between Pittsburgh and Boston in 1903 and was a best of nine-game series. Boston won the series 5-3.",
            "The New York Yankees have won a total of 27 World Series titles.",
            "Former Yankees Mickey Mantle currently holds the record for most home runs (18) and RBI (40) in World Series history.",
            "The National League and the American League played the first All-Star Game in 1933.",
            "Baltimore Orioles shortstop Cal Ripken, Jr. did not miss a game for 16 years. He played in 2,632 consecutive games.",
            "In 2001, San Francisco's slugger Barry Bonds broke the all-time single-season record for home runs when he hit 73.",
            "Nolan Ryan played 27 seasons in MLB and struck out more batters than any other pitcher in history.",
            "The National Baseball Hall of Fame is located in Cooperstown, NY. It was built in 1935 to celebrate baseball's 100th anniversary.",
            "Dr. James Naismith is credited with inventing the game of basketball in 1891.",
            "The first “rims” were actually made of peach baskets and the first backboards were made from wire.",
            "Basketball became an official Olympic event at the Berlin Olympics in 1936.",
            "Two basketball leagues; the National Basketball League (NBL) and the Basketball Association of America (BAA) merged in 1949 to become today's National Basketball Association (NBA).",
            "Kareem Abdul-Jabbar played 20 seasons in the NBA, holds the record for most points in a career (38,387).",
            "The NBA instituted the three-point shot after the 1978-79 season, an idea which was adopted from the ABA.",
            "Michael Jordan, has scored more points (5,987) in the playoffs than any other player in basketball history.",
            "The Grey Cup, the super bowl of the Canadian Football League, is given to the champion of the Canadian Football League.",
            "Beattie Feathers was the first player in NFL history who rushed for 1,000 yards in a season. He accomplished this in 1934 with the Chicago Bears.",
            "Jay Berwanger was the first winner of the Heisman trophy.",
            "The NFL Pro Bowl, has been played at Aloha Stadium in Honolulu, Hawaii since 1980.",
            "In 2001, Kansas City Chiefs running back Priest Holmes became the first undrafted player to lead the NFL in rushing.",
            "The four major events in professional golf are the British Open, the Masters, the U.S. Open, and the PGA Championship.",
            "The four major's in women's professional golf are the U.S. Open, the Women's British Open, the LPGA championship, and the Nabisco Championship.",
            "The Ryder Cup is the most prestigious team golf event. It is played every two years between a team of European golfers and a team of American golfers.",
            "The original Stanley Cup was just seven inches high. The names of every player from each winning team is engraved on the base of the Cup. The cup and base now stands 35 inches high.",
            "The Montreal Canadiens have won the most Stanley Cups, a total of 23. The Toronto Maple Leafs are second on the list with 13.",
            "The first goaltender to regularly wear a face mask during a game was Montreal's Jacques Plante.",
            "The first player who accumulate more than 300 penalty minutes in a single season was Philadelphia Flyer Dave Schultz, who had 348 penalty minuted in 1974.",
            "Canada is widely considered to be the birthplace of hockey.",
            "The Hockey Hall of Fame is in Toronto, Canada.",
            "NASCAR's biggest race, the Daytona 500 is also the first race of the year.",
            "The first Indianapolis 500 took place in 1911. It was won by Ray Harroun, who took the checkered flag with an average speed under 75 miles per hour. Current winners of the race now average between 140-186 mph.",
            "The Motorsports Hall of Fame of America is located in Novi, Michigan, and the International Motorsports Hall of Fame can be found in Talladega, Alabama.",
            "A yellow strip across the rear of a NASCAR racecar signifies a rookie driver.",
            "Playing cards were introduced in Europe in the 1300s.",
            "The French Open, Australian Open, Wimbledon, and the U.S. Open tournaments make up tennis's “Grand Slam.” If a player wins all for Grand Slams, it is called a golden slam.",
            "The first Wimbledon Championship took place in 1877 when it was watched by only 200 spectators. In 1999 it was broadcast to a toal of 174 countries, with an estimated audience of over 1 billion people.",
            "Tennis Equipment has changed over the years. Early wooden tennis rackets were replaced with graphite rackets.",
            "The silhouette on the NBA logo is Hall of Fame Laker Jerry West.",
            "The referee tossed a jump ball after every basket in basketball until 1937.",
            "In July of 1934, Babe Ruth paid a fan $20 for the return of the baseball he hit for his 700th career home run.",
            "At one point in August 1971, the Pittsburgh Pirates became the first professional team to field nine players who were either black or Latino. Coincidentally, this was the same year they won the World Series.",
            "The average life span of an MLB baseball is five to seven pitches.",
            "Track athletes are surprisingly most likely to break records late in the day, with body temperatures at their highest.",
            "Pittsburgh is the only American city with three sports teams that wear the same colors.",
            "It takes 3,000 cows to supply the NFL with enough leather for a year’s supply of footballs.",
            "Golf balls can reach speeds of 170 miles an hour.",
            "The actual playing time in an MLB game is nine minutes and 55 seconds, despite routinely finishing at around three hours.",
            "Babe Ruth wore a cabbage leaf under his cap to keep him cool and changed it every two innings.",
            "There are more than 350 dimples on a golf ball.",
            "In 1910, an incomplete forward pass earned teams a 15-yard penalty.",
            "The household wrench was invented by boxing heavyweight champion Jack Johnson in 1922.",
            "Tug of war was an Olympic event between 1900 and 1920.",
            "Michael Jordan was once one of the best high school pitchers in North Carolina.",
            "At 120 miles per hour, a Formula One car generates so much downforce that it can drive upside down on the roof of a tunnel.",
            "A microwaved baseball will fly farther than a frozen baseball.",
            "When pitched, the average MLB baseball rotates 15 times before being hit.",
            "The state sport of Maryland is jousting.",
            "Three consecutive strikes in bowling is called a turkey.",
            "Table tennis balls can travel off the paddle at 105.6 miles per hour.",
            "Prior to 1900, prize fights lasted up to 100 rounds.",
            "In 1935 Jesse Owens broke four world records in 45 minutes.",
            "People in nudist colonies play volleyball more than any other sport.",
            "Most NASCAR teams use nitrogen in their tires instead of air.",
            "Hall of Fame pitcher Jim \"Catfish\" Hunter garnered his nickname after Oakland Athletics owner Charles Finley made up a story that Hunter had caught a large catfish as a boy.",
            "Each year, 30,000 people are seriously injured by exercise equipment.",
            "Because they both lost so many players to WWII military service, the Pittsburgh Steelers and Philadelphia Eagles combined to become the Steagles during the 1943 season.",
            "At horse race tracks, the favorite wins about 30 (or less) percent of the time.",
            "A faceoff in hockey was originally called a puck-off or a face of the puck.",
            "The Kentucky Derby is the oldest continually held sports event in the United States (1875), with the second being the Westminster Kennel Club Dog show (1876).",
            "A forfeited game in baseball is recorded as 9-0.",
            "The practice of identifying baseball players by number (corresponding to a player's position in the batting order) was started by the Yankees in 1929.",
            "In 1986 Danny Heep became the first player in a World Series to be a designated hitter (DH) with the initials \"D.H.\"",
            "Kite flying is a professional sport in Thailand.",
            "The only two days of the year on which there are no professional sports games (MLB, NBA, NHL or NFL) are the day before and the day after the MLB All-Star Game.",
            "The 1912 Olympics was the last time that gold medals were solid gold.",
            "Basketball legend Wilt Chamberlain never fouled out of a game.",
            "Before 1859, umpires sat in a padded rocking chair behind the catcher.",
            "Ari Petrof is Sweden's National Sauna Champion. He stayed in a 212-degree Fahrenheit (100-degree Celsius) sauna for five hours and 10 minutes.",
            "The Dallas Cowboys hired the NFL's first professional cheerleading squad in 1972.",
            "Billiards great Henry Lewis once sank 46 balls in a row.",
            "Since 1896, the beginning of the modern Olympics, only Greece and Australia have participated in every Games.",
            "Racehorses have been known to wear out new shoes in one race.",
            "At 101, Larry Lewis ran the 100-yard dash in 17.8 seconds, setting a new world record for runners 100 years old or older.",
            "The yo-yo started out as a weapon in the Philippines during the 16th century before being introduced to the United States as a toy in 1929. It weighed four pounds and had a 20-foot cord.",
            };


    public String[] animalFacts = { //array containing animalFacts
            "All animals are made up of more than one cell (are multicellular).",
            "All animals are eukaryotes. This means that their cells have a nucleus which contains genetic material. Such cells are known as eukaryotic cells.",
            "All animals are heterotrophs - they gain energy by taking in carbon-based compounds from other organisms.",
            "All animals can move about by themselves during part or all of their lifetimes.",
            "Animals live on every continent on Earth, as well as in its oceans.",
            "Human beings are animals, of the species Homo sapiens. Our genes show that our closest living relatives are chimpanzees.",
            "The first animals to appear on Earth are believed to have been sponges. Scientists have found chemical remains of sponges that lived over 600 million years ago.",
            "Fossils show that  most major groups of animals appeared on Earth during the Cambrian explosion, about 530 million years ago.",
            "The blue whale is the largest living animal.",
            "The African elephant is the largest animal that lives on land.",
            "The largest land animals to have ever lived were dinosaurs known as sauropods.",
            "The giraffe is the tallest living animal on earth.",
            "One of the smallest animals in the world is a wasp, Dicopomorpha echmepterygis. Males are only about 1/7 of a millimeter long.",
            "The bootlace worm, a type of ribbon worm, can grow up to 200 feet long. It is the longest animal on Earth.",
            "A clam that lived to be a little over 400 years old had the longest lifespan of any animal that we know about.",
            "The gastrotrich, a microscopic animal that lives in fresh and saltwater, lives for about three days. It has the shortest lifespan of any living animal.",
            "Taxonomy is the science of classifying living things, including animals.",
            "The word 'taxonomy' comes from the Greek words taxis (arrangement) and nomos (laws), so taxonomy means the \"law of arranging\".",
            "A habitat is the natural environment in which an organism lives.",
            "Amphibians, members of the class Amphibia, include frogs, toads, salamanders, newts and caecilians.",
            "Arthropods are the group of invertebrates (animals without backbones) that includes insects, arachnids and crustaceans",
            "More than three fourths of the species that we know today are arthropods.",
            "It  is estimated that there may be tens of millions of arthropod species.",
            "Bats are the only mammals that can fly for sustained periods, using their own power.",
            "Bats use their wings to propel themselves through the air, like birds do.",
            "Birds, members of the class Aves, include some of the Earth's most intelligent animal species.",
            "Birds can be found in the wild on all seven continents.",
            "All birds are vertebrates (have backbones) and are endothermic (warm-blooded).",
            "All birds have feathers, and their front limbs have evolved to become wings.",
            "Many birds migrate to take advantage of seasonal changes in different parts of the world.",
            "Carnivorans are members of the order Carnivora, a group of placental mammals that are very well adapted for hunting and killing other animals.",
            "Carnivorans have strong, sharp claws. They have four or five toes on each foot.",
            "Some carnivorans, such as cats and weasels, are obligate carnivores. They do not have the ability to digest plant matter efficiently and are completely dependent on the nutrients found in meat.",
            "Cetaceans, members of the order Cetacea, are aquatic placental mammals (eutherians). They include whales, dolphins and porpoises.",
            "A blue whale can grow to over 100 feet long and weigh more than 200 tons.",
            "Whales, dolphins and porpoises have streamlined bodies that allow them to move through water easily. Their bodies are large in the middle and taper at the ends. This shape is known as a fusiform shape.",
            "Fish have vertical tails that move side to side when they swim.",
            "Whales, dolphins and porpoises have very little hair on their bodies.",
            "When a whale, dolphin or porpoise dives underwater, its blowhole/blowholes closes up until it comes to the surface to breathe. The blowhole/blowholes then opens so that it can inhale oxygen/exhale carbon dioxide.",
            "Some whales can stay underwater for over an hour. The blood cells and muscles of cetaceans store oxygen more efficiently than the blood cells and muscles of non-aquatic mammals.",
            "A chordate is an animal that has a notochord - a flexible rod that runs along the inside of the body - at some time in its life. Human beings are chordates.",
            "Crustaceans constitute the most diverse group of ocean-living animals on Earth. Lobsters, crabs and shrimp are crustaceans.",
            "The word \"dinosaur\" is commonly used to describe a group of amniotes that lived on Earth from about 230 million years ago to about 65 million years ago.",
            "\"Dinosaur\" is Greek for \"terrible lizard\".",
            "Some groups of extinct dinosaurs were more closely related to modern birds than they were to other groups of extinct dinosaurs.",
            "The last of the non-avian dinosaurs become extinct about 65 million years ago, along with many other species of animals and plants (this is known as the Cretaceous-Tertiary extinction event or K-T extinction event).",
            "When an animal has fingers or toes that are fused together, it is said to display a condition known as syndactyly.",
            "Elephants are the largest living land animals on Earth and among the world's most intelligent animals.",
            "The trunk of an elephant is very strong and very sensitive. It contains tens of thousands of individual muscles and is capable of very fine motor movements.",
            "Elephants have tusks - extremely long teeth that extend beyond the mouth.",
            "Elephants have large ears, which they  flap their ears to cool themselves on hot days.",
            "An elephant's diet is herbivorous (consists of plant matter).",
            "Females engage in alloparenting - caring for children that were born to other parents.",
            "Elephants have the ability to use tools, to solve complex problems and to adapt to unexpected situations.",
            "Elephants can recognize themselves in mirrors. This indicates that they are self-aware.",
            "Fish are usually streamlined in shape, so that they can move through water rapidly.",
            "If a fish has limbs, the limbs are usually in the form of fins.",
            "Most species of fish are oviparous (lay eggs) and practice external fertilization - the male fertilizes the eggs when they are outside the female's body.",
            "Most fish breathe through gills throughout their lives. They use their gills to filter dissolved oxygen from the water.",
            "Fish are usually cold-blooded (ectothermic) but some fish, such as tuna, swordfish and mackerel sharks, are able to regulate the temperature in parts of their bodies.",
            "Insects are the most diverse group of animals on Earth.",
            "The majority of known animal species are insects.",
            "There may be as many as 10 million different insect species.",
            "Most insects live in land, although a few live in water.",
            "The first mammals appeared on Earth between about 200 and 250 million years ago.",
            "All mammals have fur or hair during part or all of their lives.",
            "Female mammals have mammary glands (a type of sweat gland) which produce milk, a substance that is used to feed young.",
            "A mammal's heart has four chambers.",
            "A mammal's mouth contains teeth that have different shapes so that they can perform different functions.",
            "Mammals have four basic kinds of  teeth - incisors, canines, premolars and molars.",
            "Primates have large brains in comparison to their body size.",
            "The first primates, who lived between 65 and 85 million years ago, lived in trees.",
            "Reptiles include snakes, lizards, alligators, crocodiles, caimans, gharials, false gharials, tuataras, turtles, tortoises and terrapins.",
            "The word reptile comes from the Latin word for \"creeping\" or \"crawling\".",
            "A reptile's skin is watertight and covered with dry scales.",
            "Reptiles are cold-blooded (ectothermic).",
            "The largest reptile in the world today is the saltwater crocodile (Crocodylus porosus), which lives in India, Southeast Asia and Australia. An adult male can grow up to 17 feet long.",
            "There are over 2000 species of rodent. There are more rodent species than species of any other type of mammal. Rodents make up 40% of all mammal species.",
            "Rodents can be found on every continent except Antarctica.",
            "While many rodents are small, the capybara, the largest living rodent on Earth, can weigh more than 100 pounds.",
            "The African pygmy mouse and the pygmy jerboa, two of the world's smallest rodents, weigh less than half an ounce.",
            "The average male cheetah reaches speeds of 65mph.",
            "In total there is said to be around 400 million dogs in the world.",
            "Although experts often disagree, there is scientific evidence which shows that the domestication of dogs could have occurred more than 15,000 years ago.",
            "The most popular breed of dog in the world by registered ownership is the Labrador.",
            "Dog have superior hearing than humans, capable of hearing sounds at four times the distance.",
            "Dogs have a remarkable sense of smell, they are capable of differentiating odors in concentrations nearly 100 million times lower than humans can.",
            "The average life span for a dog is around 10 to 14 years.",
            "Domestic dogs are omnivores, they feed on a variety of foods including grains, vegetables and meats.",
            "There are over 500 million domestic cats in the world.",
            "Cats conserve energy by sleeping for an average of 13 to14 hours a day.",
            "Cats have flexible bodies and teeth adapted for hunting small animals such as mice and rats.",
            "Domestic cats usually weigh around 4 kilograms (8 lb 13 oz) to 5 kilograms (11 lb 0 oz).",
            "The heaviest domestic cat on record is 21.297 kilograms (46 lb 15.2 oz).",
            "Cats have powerful night vision, allowing them to see at light levels six times lower than what a human needs in order to see.",
            "On average cats live for around 12 to 15 years.",
            "Cats spend a large amount of time licking their coats to keep them clean.",
            "The tiger is the biggest species of the cat family.",
            "Tigers can reach a length of up to 3.3 metres (11 feet) and weigh as much as 300 kilograms (660 pounds).",
            "Subspecies of the tiger include the Sumatran Tiger, Siberian Tiger, Bengal Tiger, South China Tiger, Malayan Tiger and Indochinese Tiger.",
            "Around half of tiger cubs don’t live beyond two years of age.",
            "Tiger cubs leave their mother when they are around 2 years of age.",
            "Rare white tigers carry a gene that is only present in around 1 in every 10000 tigers.",
            "Tigers usually hunt alone at night time.",
            "Tigers have been known to reach speeds up to 65 kph (40 mph).",
            "Various tiger subspecies are the national animals of Bangladesh, India, North Korea, South Korea and Malaysia.",
            "There are more tigers held privately as pets than there are in the wild.",
            "Tigers that breed with lions give birth to hybrids known as tigons and ligers.",
            "Sharks do not have a single bone in their bodies. Instead they have a skeleton made up of cartilage; the same type of tough, flexible tissue that makes up human ears and noses.",
            "Some sharks remain on the move for their entire lives. This forces water over their gills, delivering oxygen to the blood stream. If the shark stops moving then it will suffocate and die.",
            "Sharks have outstanding hearing. They can hear a fish thrashing in the water from as far as 500 meters away!",
            "If a shark was put into a large swimming pool, it would be able to smell a single drop of blood in the water.",
            "Lions are the second largest big cat species in the world (behind tigers).",
            "The average male lion weighs around 180 kg (400 lb) while the average female lion weighs around 130 kg (290 lb).",
            "The roar of a lion can be heard from 8 kilometers (5.0 miles) away.",
            "A gorilla can live for 40 – 50 years.",
            "Gorillas are considered to be very intelligent animals. They are known for their use of tools and their varied communication. Some gorillas in captivity at a zoo have been taught to use sign language.",
            "The hair that makes up a giraffes tail is about 10 times thicker than the average strand of human hair.",
            "The distinctive spots that cover a giraffe’s fur act as a good camouflage to protect the giraffe from predators.",
            "Giraffes are ruminants. This means that they have more than one stomach. In fact, giraffes have four stomachs, the extra stomachs assisting with digesting food.",
            "The wolf is the ancestor of all breeds of domestic dog. It is part of a group of animals called the wild dogs which also includes the dingo and the coyote.",
            "A leopard’s tail is just about as long as its entire body. This helps it with balance and enables it to make sharp turns quickly.",
            "Leopards are mostly nocturnal, hunting prey at night.",
            };

    int i = 0; //counter
    String fact; //,snappleFactsType, historyFactsType, sportsFactsType, animalsFactsType; //declaring String fact
    int[] randomNoRepeatArray; //declaring randomNoRepeatArray and giving it values based on getRandNumArray of the RandomNoRepeat.java class
    String[] factsArray; //initializes factsArray which takes value of one of the arrays

    int[] snappleFactsRandom = randomNoRepeat.getRandNumArray(snappleFacts.length); //gives random values with no repeat to array
    int[] historyFactsRandom = randomNoRepeat.getRandNumArray(historyFacts.length); //gives random values with no repeat to array
    int[] animalFactsRandom = randomNoRepeat.getRandNumArray(animalFacts.length); //gives random values with no repeat to array
    int[] sportsFactsRandom = randomNoRepeat.getRandNumArray(sportsFacts.length); //gives random values with no repeat to array

    public String getFacts(String factBookType) { //get method to obtain fact on click

        if (factBookType == "snappleFactsType") { //if statement to determine array to extract facts from
            factsArray = snappleFacts;
            randomNoRepeatArray = snappleFactsRandom;
        } else if (factBookType == "historyFactsType") {
            factsArray = historyFacts;
            randomNoRepeatArray = historyFactsRandom;
        } else if (factBookType == "sportsFactsType") {
            factsArray = sportsFacts;
            randomNoRepeatArray = sportsFactsRandom;
        } else if (factBookType == "animalFactsType") {
            factsArray = animalFacts;
            randomNoRepeatArray = animalFactsRandom;
        }

        if (i < (randomNoRepeatArray.length)) { //loops through all facts
            fact = factsArray[randomNoRepeatArray[i] - 1]; //pulls facts from SnappleFacts array; subtract -1 because randomNoRepeatArray[0]=1
        } else { //this will happen once all facts have been displayed
            fact = "Those are all the facts for this category for now... Check out another category!";
        }
        i++; //counter after each loop
        return fact; //returns fact to SnappleFactsActivity
    }
}
